# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa40cf1780724e9c964de4cb80cb75be2aed41f09b6db07a7bf8863cca317cf2b309e9b17ed566a3278d1c87b7be3adf13363a0742ccf0e4820acc05545c6779

test:
  secret_key_base: bdf619b86573f0d4d2e3c5a9cedeec60c784e98fbf9f59895a5f9c5730afe3a008f5fe7625607f8ad3c1271d6888f227bec2adcdd23707902e8c915c5cb191ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
